#!/usr/bin/ruby
# option parser template: https://gist.github.com/rtomayko/1190547

require "optparse"

require_relative 'lib/converter'
require_relative 'lib/entities'
# require_relative 'lib/operations'
require_relative 'lib/generators'

# convert-feed --out rss feed.xml
# convert-feed --out atom https://ru.hexlet.io/lessons.rss

options = {}

# parse arguments
file = __FILE__
ARGV.options do |opts|
  opts.on("-r", "--reverse")            { options[:reverse] = true }
  opts.on("-s", "--sort")               { options[:sort] = true }
  opts.on("-o", "--out=format", String) { |val| options[:format] = val }
  opts.on("-l", "--limit=val", Integer) { |val| options[:limit] = val }
  opts.on_tail("-h", "--help")          { exec "grep ^#/<'#{file}'|cut -c4-" }
  opts.parse!
end

output = Converter.new(options).convert(ARGV.first)
puts output.inspect

# TODO:
#  - standard gem structure
#  - get rid of classes Feed, Info, Item
#  - meningful tests